baseURL = "https://islandsprite.com/"
languageCode = "en-us"
title = "Island Sprite"
theme = "researcher"
disableKinds = ["taxonomy", "term"]
enableEmoji = true
math = false          # enable KaTeX (https://katex.org/) globally
googleAnalytics = ""  # add your tracking id

[params]
  author = "Cameron Holiman"
  description = "Island Sprite"
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  avatar = "avatar.jpg"
  [params.footer]
    text = "By Cameron Holiman"

[permalinks]
  "/" = "/:filename"

[menu]
  [[menu.main]]
    name = "Apps"
    url = "/apps"
    weight = 1
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 2

[markup.goldmark.renderer]
  unsafe = true  # allow raw HTML in markdown files
